export const StringResources = {
  ClienteNomeObrigatorio: 'O nome é obrigatório.',
  ClienteNomeMaximoCaracteres: 'O nome deve possuir no máximo 150 caracteres.',
  ClienteNomeDeveConterMaisDeUmNome: 'Informe nome e sobrenome (mais de um nome).',
  ClienteEmailObrigatorio: 'O e-mail é obrigatório.',
  ClienteEmailInvalido: 'O e-mail informado é inválido.',
  ClienteEmailMaximoCaracteres: 'O e-mail deve possuir no máximo 150 caracteres.',
  ClienteTelefoneObrigatorio: 'O telefone é obrigatório.',
  ClienteTelefoneInvalido: 'O telefone informado é inválido.',
  ClienteTelefoneMaximoCaracteres: 'O telefone deve possuir no máximo 11 dígitos.',
  ClienteCpfCnpjObrigatorio: 'O CPF ou CNPJ é obrigatório.',
  ClienteCpfCnpjInvalido: 'O CPF ou CNPJ informado é inválido.',
  ClienteObservacaoMaximoCaracteres: 'A observação deve possuir no máximo 500 caracteres.',
  ClienteSenhaObrigatoria: 'A senha é obrigatória.',
  SenhaDeveTerMinimoCaracteres: 'A senha deve possuir no mínimo 10 caracteres.',
  ClienteSenhaDeveConterLetras: 'A senha deve conter letras.',
  ClienteSenhaDeveConterLetraMaiuscula: 'A senha deve conter pelo menos uma letra maiúscula.',
  ClienteSenhaDeveConterCaractereEspecial: 'A senha deve conter pelo menos um caractere especial.',
  ClienteSenhaNaoPodeConterNumerosSequenciais: 'A senha não pode conter números sequenciais (ex.: 1234).',
  ClienteConfirmacaoSenhaObrigatoria: 'A confirmação da senha é obrigatória.',
  ClienteConfirmacaoSenhaInvalida: 'A confirmação de senha deve ser igual à senha.',
  ClienteErroComunicacaoBackend: 'Erro ao comunicar com a API de backend.',
  ClienteCadastroSucesso: 'Cliente cadastrado com sucesso. Código: {0}.',
  LoginIdentificadorObrigatorio: 'Informe E-mail ou CPF/CNPJ.',
  LoginIdentificadorInvalido: 'Informe um E-mail ou CPF/CNPJ válido.',
  LoginSenhaObrigatoria: 'A senha é obrigatória.',
  LoginErroComunicacaoBackend: 'Erro ao comunicar com a API de backend durante o login.',
  ModuloClienteTitulo: 'Módulo Cliente',
  GerencialTitulo: 'Gerencial',
  UsuarioAutenticadoLabel: 'Usuário autenticado:'
} as const;
